import type { OperationsWorkspace, PropertyCommandCenter } from "../lib/types";

export const fixturePropertyId = "10000000-0000-4000-8000-000000000001";

export const fixtureCenter: PropertyCommandCenter = {
  property: {
    id: fixturePropertyId,
    title: "Casa piloto Castro",
    description: "Casa luminosa preparada para comercialización.",
    operation_type: "rent",
    property_type: "house",
    city: "Castro",
    sector: "Centro",
    monthly_price: 720000,
    sale_price: null,
    currency: "CLP",
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 1,
    pet_policy: "allowed",
    furnished: false,
    square_meters: 94,
    reference_code: "PILOT-001",
    built_area_m2: 94,
    land_area_m2: 180,
    commercial_status: "active",
    amenities: ["patio"],
    availability_status: "available",
    source_text: "Ficha piloto",
    created_at: "2026-09-18T12:00:00Z",
    updated_at: "2026-09-18T12:00:00Z",
  },
  demo_mode: true,
  channel_accounts: [],
  distribution: [{
    target: {
      id: "target-1",
      name: "Corredores de Castro",
      channel_type: "facebook_group",
      execution_mode: "assisted",
      channel_account_id: null,
      destination_url: "https://example.invalid/group",
      geographic_relevance: "Castro",
      property_tags: [],
      active: true,
      minimum_repost_interval_hours: 72,
      notes: null,
      is_demo: true,
    },
    job: {
      id: "job-1",
      campaign_id: "campaign-1",
      property_id: fixturePropertyId,
      target_id: "target-1",
      package_id: "package-1",
      variant_type: "facebook_group",
      execution_mode: "assisted",
      status: "ready",
      scheduled_at: "2026-09-18T12:00:00Z",
      next_eligible_at: null,
      attempt_count: 0,
      error_code: null,
      error_message: null,
      action_required: false,
      action_note: null,
    },
    latest_publication: null,
    package_variant: {
      id: "variant-1",
      package_id: "package-1",
      channel_type: "facebook_group",
      headline: "Casa en arriendo en Castro",
      body: "Casa luminosa de 3 dormitorios en Castro centro.",
      short_body: "Casa en Castro",
      highlights: ["3 dormitorios", "$720.000 mensuales"],
      cta: "Coordina una visita.",
      suggested_media_ids: [],
      warnings: [],
    },
    prepared_media: [],
    status: "ready",
    last_publication_at: null,
    next_eligible_at: null,
    publication_url: null,
    action_required: false,
    capabilities: [{ capability: "assisted_publish", availability: "assisted_only", reason: null }],
  }],
  engagement: {
    comments_count: 1,
    reactions_count: 3,
    views_count: null,
    impressions_count: null,
    messages_count: 1,
    last_captured_at: "2026-09-18T12:00:00Z",
  },
  engagement_snapshots: [],
  recent_comments: [],
  related_conversations: [{
    id: "conversation-1",
    channel_account_id: "account-1",
    channel_type: "messenger",
    property_id: fixturePropertyId,
    publication_id: null,
    lead_id: null,
    status: "needs_reply",
    last_message_at: "2026-09-18T12:30:00Z",
    is_demo: true,
    messages: [{
      id: "message-1",
      direction: "inbound",
      sender_display_name: "Daniela",
      message_type: "text",
      body: "Hola, ¿sigue disponible?",
      sent_at: "2026-09-18T12:30:00Z",
      is_demo: true,
    }],
  }],
  next_actions: [{
    type: "initial_publication",
    priority: "medium",
    title: "Publicar en Corredores de Castro",
    description: "El contenido está listo para publicar.",
    related_entity_type: "publication_target",
    related_entity_id: "target-1",
  }],
  campaigns: [{
    id: "campaign-1",
    status: "active",
    created_at: "2026-09-18T12:00:00Z",
    publications: [],
    jobs: [],
  }],
};

export const fixtureWorkspace: OperationsWorkspace = {
  properties: [fixtureCenter.property],
  centers: [fixtureCenter],
  demo_mode: true,
};
